DROP DATABASE IF EXISTS OMOK;
CREATE DATABASE OMOK;

USE OMOK;

DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER` (
	`U_KEY`	INT	NOT NULL,
	`U_ID`	CHAR(20) NOT NULL	NULL,
	`U_PW`	CHAR(20) NOT NULL	NULL,
	`U_NAME`	CHAR(20) NOT NULL	NULL
);

DROP TABLE IF EXISTS `OMOK_RESELT`;

CREATE TABLE `OMOK_RESELT` (
	`G_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`G_COLOR`	CHAR(10)	NULL,
	`G_COUNT`	INT	NULL,
	`G_DATE`	DATE	NULL,
	`G_RESULT`	CHAR(10)	NULL,
	`G_U_KEY`	INT	NOT NULL
);


ALTER TABLE `OMOK_RESELT` ADD CONSTRAINT `FK_USER_TO_OMOK_RESELT_1` FOREIGN KEY (
	`G_U_KEY`
)
REFERENCES `USER` (
	`U_KEY`
);
