DROP DATABASE IF EXISTS OMOK;
CREATE DATABASE OMOK;

USE OMOK;

DROP TABLE IF EXISTS `USER`;

CREATE TABLE `USER` (
	`U_ID`	VARCHAR(20) PRIMARY KEY	NOT NULL,
	`U_PW`	VARCHAR(20) NOT	NULL,
	`U_NAME`	VARCHAR(20) UNIQUE NOT	NULL
);

DROP TABLE IF EXISTS `OMOK_RESELT`;

CREATE TABLE `OMOK_RESELT` (
	`G_NUM`	INT PRIMARY KEY AUTO_INCREMENT	NOT NULL,
	`G_U_ID`	VARCHAR(20) ,
	`G_COLOR`	ENUM("B","W") DEFAULT "B" NOT	NULL,
	`G_COUNT`	INT DEFAULT 0 NOT	NULL,
	`G_DATE`	DATETIME DEFAULT CURRENT_TIMESTAMP NOT	NULL,
	`G_RESULT`	ENUM("W","L") DEFAULT "L" NOT	NULL
);

ALTER TABLE `OMOK_RESELT` ADD CONSTRAINT `FK_USER_TO_OMOK_RESELT_1` FOREIGN KEY (
	`G_U_ID`
)
REFERENCES `USER` (
	`U_ID`
);

