USE OMOK;

DROP PROCEDURE IF EXISTS RATING;

DELIMITER //
CREATE PROCEDURE RATING(
	IN U_NAME VARCHAR(10)
    
)
BEGIN
	SELECT  S_U_NAME 유저,
			S_POSITION 진영,
			((S_WIN)/(S_COUNT))*100 AS 승률
    
    FROM SCORE
    WHERE
		S_U_NAME = U_NAME;
   
END //
DELIMITER ;

DROP PROCEDURE IF EXISTS RATING_ALL;

DELIMITER //
CREATE PROCEDURE RATING_ALL(
	IN U_NAME VARCHAR(10)
    
)
BEGIN
	SELECT  S_U_NAME 유저,
			(SUM(S_WIN)/SUM(S_COUNT))*100 AS 승률
    
    FROM SCORE
    WHERE
		S_U_NAME = U_NAME;
   
END //
DELIMITER ;

DROP PROCEDURE IF EXISTS ODDS_OF_WINNING;

DELIMITER //
CREATE PROCEDURE ODDS_OF_WINNING(
	IN U_NAME VARCHAR(10),
    IN BLACK_WIN INT,
	IN WHITE_WIN INT,
    IN WIN_ALL INT
)
BEGIN
	DECLARE BLACK INT;
    DECLARE WHITE INT;
    DECLARE W_ALL INT;
    
    SET BLACK = (SELECT ((S_WIN)/(S_COUNT))*100
    FROM SCORE
    WHERE S_POSITION = "BLACK");
    
	SET WHITE = (SELECT ((S_WIN)/(S_COUNT))*100
    FROM SCORE
    WHERE S_POSITION="WHITE");
    
    SET W_ALL = ((BLACK+WHITE)/2);
  
END //
DELIMITER ;

SELECT * FROM omok.score;
CALL RATING("박소은");